# Generated by Django 4.0 on 2022-05-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_background_picture.png', upload_to=''),
        ),
    ]
