# Generated by Django 4.0 on 2022-05-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reply_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-id']},
        ),
    ]
